// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZS_Backend.API.Data;

#nullable disable

namespace ZS_Backend.API.Migrations
{
    [DbContext(typeof(ZsDbContext))]
    [Migration("20260121084213_Add Transactions")]
    partial class AddTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZS_Backend.API.Models.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ZS_Backend.API.Models.Domain.Locker", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastAssignedTo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LastAssignedTo");

                    b.ToTable("Lockers");

                    b.HasData(
                        new
                        {
                            Id = "1H",
                            Available = true
                        },
                        new
                        {
                            Id = "2H",
                            Available = true
                        },
                        new
                        {
                            Id = "3H",
                            Available = true
                        },
                        new
                        {
                            Id = "4H",
                            Available = true
                        },
                        new
                        {
                            Id = "5H",
                            Available = true
                        },
                        new
                        {
                            Id = "6H",
                            Available = true
                        },
                        new
                        {
                            Id = "7H",
                            Available = true
                        },
                        new
                        {
                            Id = "8H",
                            Available = true
                        },
                        new
                        {
                            Id = "9H",
                            Available = true
                        },
                        new
                        {
                            Id = "10H",
                            Available = true
                        },
                        new
                        {
                            Id = "11H",
                            Available = true
                        },
                        new
                        {
                            Id = "12H",
                            Available = true
                        },
                        new
                        {
                            Id = "13H",
                            Available = true
                        },
                        new
                        {
                            Id = "14H",
                            Available = true
                        },
                        new
                        {
                            Id = "15H",
                            Available = true
                        },
                        new
                        {
                            Id = "16H",
                            Available = true
                        },
                        new
                        {
                            Id = "1M",
                            Available = true
                        },
                        new
                        {
                            Id = "2M",
                            Available = true
                        },
                        new
                        {
                            Id = "3M",
                            Available = true
                        },
                        new
                        {
                            Id = "4M",
                            Available = true
                        },
                        new
                        {
                            Id = "5M",
                            Available = true
                        },
                        new
                        {
                            Id = "6M",
                            Available = true
                        },
                        new
                        {
                            Id = "7M",
                            Available = true
                        },
                        new
                        {
                            Id = "8M",
                            Available = true
                        },
                        new
                        {
                            Id = "9M",
                            Available = true
                        },
                        new
                        {
                            Id = "10M",
                            Available = true
                        },
                        new
                        {
                            Id = "11M",
                            Available = true
                        },
                        new
                        {
                            Id = "12M",
                            Available = true
                        },
                        new
                        {
                            Id = "13M",
                            Available = true
                        },
                        new
                        {
                            Id = "14M",
                            Available = true
                        },
                        new
                        {
                            Id = "15M",
                            Available = true
                        },
                        new
                        {
                            Id = "16M",
                            Available = true
                        });
                });

            modelBuilder.Entity("ZS_Backend.API.Models.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ZS_Backend.API.Models.Domain.Locker", b =>
                {
                    b.HasOne("ZS_Backend.API.Models.Domain.Client", "LastAssignedClient")
                        .WithMany()
                        .HasForeignKey("LastAssignedTo");

                    b.Navigation("LastAssignedClient");
                });

            modelBuilder.Entity("ZS_Backend.API.Models.Domain.Transaction", b =>
                {
                    b.HasOne("ZS_Backend.API.Models.Domain.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
